# Generated by Django 4.2.13 on 2024-06-17 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': (['myuser', '审核用户信息'],), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
